--03/02/2026
--@PLima
--Obtendo dados do paciente usando a Prescricao médica
SELECT
    PM.NR_PRESCRICAO,
    PM.CD_PESSOA_FISICA,    
    PF.NM_SOCIAL,
    PF.NM_PESSOA_FISICA,
    PM.NR_ATENDIMENTO,
    PM.CD_MEDICO,
    PM.DT_PRESCRICAO,
    PM.DT_ATUALIZACAO,
    PM.NM_USUARIO,
    PM.DT_LIBERACAO,
    PF.CD_PESSOA_FISICA,
    PF.IE_TIPO_PESSOA,
    PF.DT_NASCIMENTO,
    PF.IE_SEXO,
    PF.IE_ESTADO_CIVIL,
    PF.NR_CPF,
    PF.NR_IDENTIDADE,
    PF.NR_TELEFONE_CELULAR,
    PF.NR_PRONTUARIO
FROM
    PRESCR_MEDICA PM
INNER JOIN PESSOA_FISICA PF ON PM.CD_PESSOA_FISICA = PF.CD_PESSOA_FISICA
WHERE 1 = 1
AND PM.NR_PRESCRICAO = :NR_PRESCRICAO
--teste
--AND PM.NR_PRESCRICAO = 6788792